import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderPage from "./components/HeaderPage";
import "./injectAtRoot.js";
import LoadingBar from "./components/LoadingBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

//className={`${geistSans.variable} ${geistMono.variable} antialiased`}

export const metadata = {
  title: "TMS Web App",
  description: "Generated by SUNSoft Technologies",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <HeaderPage />
        <main className="flex min-h-screen flex-col items-center">
          <LoadingBar />
          {children}
        </main>
      </body>
    </html>
  );
}
